# Generated by Django 3.0.7 on 2021-04-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='event_date',
        ),
    ]
